### ISSUE TITLE
install.sh: Host is not reachable

### ISSUE THREAD

**Issue by mirhec** [mamiu/dotfiles#3]
I clone the repo, cd into the install directory and run install.sh. Then I choose to install a new remote host. I type in the IP address of my host, but the script tells me the host is not reachable. But I can reach it via ssh and ping it manually.

**Comment by paulmiu** [comment]
If you can ping the IP address of the remote host, the install script should accept it.

Here's the code where the script checks the accessibility of the remote host:
https://github.com/mamiu/dotfiles/blob/d1ded9f87898621232fc2aba5264c348838b28e8/install/install.sh#L33

Can you please call the ping command manually:

    ping -c1 -W1 <REMOTE_HOST>

And then check the exit code (in bash) with:

    echo $?

What is the output and the exit code of the ping command?

**Comment by mirhec** [comment]
It's kind of confusing, but after I reinstalled my server (Fedora 26) and trying it again, everything worked as expected ... so I close this issue.

**Comment by paulmiu** [comment]
Ok. If the error occurs again, let me know the output from the commands above.
