### ISSUE TITLE
Open Source License

### ISSUE THREAD

**Issue by neelrr1** [mamiu/dotfiles#7]
I would like to use your `multiselect` shell implementation in a project of mine, but I don't see an open source license for this repo. Would you be open to adding one?

The MIT License (https://choosealicense.com/licenses/mit/) is pretty standard for stuff like this. A license file in the source code or a mention in the repo would help out any other developers trying to do this as well!

**Comment by paulmiu** [comment]
Thanks @neelrr1 for asking. Just added it.
